package edu.awt.hibernet.model;
// Generated Jun 4, 2017 8:29:42 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Option generated by hbm2java
 */
@Entity
@Table(name = "option", catalog = "mcqs")
public class Option implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)	
	@Column(name = "sno", unique = true, nullable = false)
	private int sno;
	
	@Column(name = "qno", nullable = false)
	private int qno;
	
	@Column(name = "ano", nullable = false)
	private int ano;
	
	@Column(name = "text", nullable = false, length = 200)
	private String text;

	public Option() {
	}

	public Option(int sno, int qno, int ano, String text) {
		this.sno = sno;
		this.qno = qno;
		this.ano = ano;
		this.text = text;
	}

	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	public int getQno() {
		return this.qno;
	}

	public void setQno(int qno) {
		this.qno = qno;
	}

	public int getAno() {
		return this.ano;
	}

	public void setAno(int ano) {
		this.ano = ano;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}
	
	@OneToMany(cascade=CascadeType.ALL, mappedBy="pk.option")
	private List<Selectoption> selectoption = new ArrayList<Selectoption>();

	public List<Selectoption> getSelectoption() {
		return selectoption;
	}

	public void setSelectoption(List<Selectoption> selectoption) {
		this.selectoption = selectoption;
	}


}
