package edu.awt.hibernet.model;
// Generated Jun 4, 2017 8:29:42 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "mcqs")
public class Question implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)	
	@Column(name = "qno", unique = true, nullable = false)
	private int qno;
	
	@Column(name = "text", nullable = false, length = 200)
	private String text;
	
	@Column(name = "cano", nullable = false)
	private int cano;

	public Question() {
	}

	public Question(int qno, String text, int cano) {
		this.qno = qno;
		this.text = text;
		this.cano = cano;
	}

	
	public int getQno() {
		return this.qno;
	}

	public void setQno(int qno) {
		this.qno = qno;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public int getCano() {
		return this.cano;
	}

	public void setCano(int cano) {
		this.cano = cano;
	}
	
	@OneToMany(cascade=CascadeType.ALL, mappedBy="pk.question")
	private List<Selectoption> selectoption = new ArrayList<Selectoption>();

	public List<Selectoption> getSelectoption() {
		return selectoption;
	}

	public void setSelectoption(List<Selectoption> selectoption) {
		this.selectoption = selectoption;
	}

}
